# Generated by Django 5.1.2 on 2024-11-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subprocesso', models.CharField(max_length=200)),
                ('parent_subprocesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos_filhos', to='processo.subprocesso')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_processo', models.CharField(max_length=200)),
                ('ferramenta_utilizada', models.CharField(max_length=400)),
                ('responsavel', models.CharField(max_length=400)),
                ('documentacao', models.CharField(max_length=400)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='area.area')),
                ('subprocessos', models.ManyToManyField(blank=True, related_name='processos', to='processo.subprocesso')),
            ],
        ),
    ]
