# Generated by Django 5.1.2 on 2024-11-07 17:14

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_processo', models.CharField(max_length=200)),
                ('ferramenta_utilizada', models.CharField(max_length=400)),
                ('responsavel', models.CharField(max_length=400)),
                ('documentacao', models.CharField(max_length=400)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='area.area')),
            ],
        ),
        migrations.CreateModel(
            name='SubProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subprocesso', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Andamento'), ('C', 'Concluído'), ('X', 'Cancelado')], default='P', max_length=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent_subprocesso', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos_filhos', to='processo.subprocesso')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='processo.processo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
