# Generated by Django 5.1.2 on 2024-11-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='subprocesso',
        ),
        migrations.AlterField(
            model_name='subprocesso',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='processo.processo'),
        ),
    ]
