# Generated by Django 5.1.2 on 2024-11-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='subprocessos',
            new_name='subprocesso',
        ),
    ]
