# Generated by Django 5.1.2 on 2024-11-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_rename_parent_subprocesso_subprocesso_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subprocesso',
            old_name='parent',
            new_name='parent_subprocesso',
        ),
    ]
