# Generated by Django 5.1.2 on 2024-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_remove_processo_subprocesso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprocesso',
            name='processo',
        ),
        migrations.AddField(
            model_name='processo',
            name='subprocesso',
            field=models.ManyToManyField(blank=True, related_name='processos', to='processo.subprocesso'),
        ),
    ]
