# Generated by Django 5.1.2 on 2024-11-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_rename_parent_subprocesso_parent_subprocesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subprocesso',
            old_name='parent_subprocesso',
            new_name='parent',
        ),
    ]
