# Generated by Django 5.1.2 on 2024-11-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_remove_subprocesso_processo_processo_subprocesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='subprocesso',
        ),
        migrations.AddField(
            model_name='subprocesso',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessos', to='processo.processo'),
        ),
    ]
