# Generated by Django 5.1.2 on 2024-11-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_subprocesso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocesso',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='processo.processo'),
        ),
    ]
