# Generated by Django 5.1.2 on 2024-11-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('processo', '0007_alter_subprocesso_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='area.area'),
        ),
    ]
